spring:
  config:
    import: "classpath:security.yaml"
  application:
    name: authserver
  web:
    error:
      whitelabel:
        enabled: false
      include-message: always

server:
  port: ${PORT:8080}

springdoc:
  swagger-ui:
    use-root-path: true

logging:
  file:
    path: ./logs
  level:
    root: INFO
    br.pucpr: DEBUG
