spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://${RDS_HOSTNAME}:${RDS_PORT:5432}/${RDS_DB_NAME:authserver}
    username: ${RDS_USERNAME}
    password: ${RDS_PASSWORD}
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update
    show-sql: false
  web:
    error:
      include-binding-errors: always
      include-stacktrace: on_param
      include-exception: true

server:
  port: ${PORT:8080}
